version: 0.0
os: windows
files:
  - source: \index.html
    destination: C:\inetpub\wwwroot\index.html
hooks:
  BeforeInstall:
    - location: scripts\install_dependencies.ps1
      timeout: 300
      runas: Administrator
    - location: scripts\stop_server.ps1
      timeout: 300
      runas: Administrator
    - location: scripts\start_server.ps1
      timeout: 300
      runas: Administrator
  ApplicationStop:
    - location: scripts\stop_server.ps1
      timeout: 300
      runas: Administrator
